# Consolidated SWR Detection Pipeline Configuration

# General Settings
run_name: $RUN_NAME 
# Unified output directory
output_dir: $OUTPUT_DIR
# Dataset-specific pool sizes
pool_sizes:
  abi_visual_behaviour: 6  
  abi_visual_coding: 6
  ibl: 2

# Thresholds (common across all pipelines)
gamma_event_thresh: 3
ripple_band_threshold: 2
movement_artifact_ripple_band_threshold: 2
merge_events_offset: 0.025  # For merging nearby events

# Common Filter Parameters
save_lfp: true
minimum_ripple_num: 100
global_no_gamma: True

# Paths to Filters
filters:
  gamma_filter: 'Filters/frank2008_gamma_1500hz_bandpass_filter.npz'
  sw_component_filter: 'Filters/sharpwave_componenet_8to40band_1500hz_band.npz'

# ABI-specific Settings (Allen Brain Institute)
abi_visual_coding:
  # Cache and data directories
  sdk_cache_dir: $ABI_VISUAL_CODING_SDK_CACHE
  swr_output_dir: 'allen_viscoding_swr_murphylab2024'
  
  # Session selection
  only_brain_observatory_sessions: False
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/allen_viscoding_swr_murphylab2024'
    swr_output_dir: 'allen_viscoding_swr_murphylab2024'
  
  # Global ripple detection
  global_ripple:
    input_dir: '${output_dir}/allen_viscoding_swr_murphylab2024'
    output_dir: '.'
    global_rip_label: 'no_movement'

# ABI-specific Settings (Allen Brain Institute)
abi_visual_behaviour:
  # Cache and data directories
  sdk_cache_dir: $ABI_VISUAL_BEHAVIOUR_SDK_CACHE
  swr_output_dir: 'allen_visbehave_swr_murphylab2024'
  
  # Session selection
  only_brain_observatory_sessions: False
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/allen_visbehave_swr_murphylab2024'
    swr_output_dir: 'allen_visbehave_swr_murphylab2024'
  
  # Global ripple detection
  global_ripple:
    input_dir: '${output_dir}/allen_visbehave_swr_murphylab2024'
    output_dir: '.'
    global_rip_label: 'no_movement'


# IBL-specific Settings
ibl:
  # Cache and data directories
  oneapi_cache_dir: $IBL_ONEAPI_CACHE
  swr_output_dir: 'ibl_swr_murphylab2024'
  
  # Input files
  session_npz_filepath: 'all_ibl_sessions_with_ca1.npz'
  
  # Session selection
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/ibl_swr_murphylab2024'
    swr_output_dir: 'ibl_swr_murphylab2024'
  
  # Global ripple detection
  global_ripple:
    input_dir: '${output_dir}/ibl_swr_murphylab2024'
    output_dir: '.'
    global_rip_label: 'no_movement_no_gamma'
