# Consolidated SWR Detection Pipeline Configuration

# General Settings
run_name: 'on_the_cluster'
# Unified output directory
output_dir: '/space/scratch/SWR_final_pipeline/testing_dir'
# Dataset-specific pool sizes
pool_sizes:
  ibl: 2
  abi: 6  # Changed from 'allen' to 'abi' to match code

# Thresholds (common across both pipelines)
gamma_event_thresh: 3
ripple_band_threshold: 2
movement_artifact_ripple_band_threshold: 2
merge_events_offset: 0.025  # For merging nearby events

# Common Filter Parameters
save_lfp: true
minimum_ripple_num: 100
global_no_gamma: True

# Paths to Filters
filters:
  gamma_filters:
    ibl: '/home/acampbell/Stienmetz2019Reanalyzed/PowerBandFilters/swr_detection_script_filters_1500Hz/frank2008_gamma_1500hz_bandpass_filter.npz'
    allen: '/home/acampbell/NeuropixelsLFPOnRamp/PowerBandFilters/swr_detection_script_filters_1500Hz/frank2008_gamma_1500hz_bandpass_filter.npz'  # Keep original key for backward compatibility
  theta_filter: '/home/acampbell/NeuropixelsLFPOnRamp/PowerBandFilters/swr_detection_script_filters_1500Hz/theta_1500hz_bandpass_filter.npz'

# IBL-specific Settings
ibl:
  # Cache and data directories
  oneapi_cache_dir: '/space/scratch/IBL_data_cache'
  swr_output_dir: 'ibl_swr_murphylab2024'
  
  # Input files
  session_npz_filepath: 'all_ibl_sessions_with_ca1.npz'
  
  # Session selection
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/ibl_swr_murphylab2024'
    swr_output_dir: 'ibl_swr_murphylab2024'
  
  # Global ripple detection
  global_ripple:
    input_dir: '${output_dir}/ibl_swr_murphylab2024'
    output_dir: '.'
    global_rip_label: 'no_movement_no_gamma'

# ABI-specific Settings (Allen Brain Institute)
abi:
  # Cache and data directories
  sdk_cache_dir: '/space/scratch/allen_visbehave_data'
  swr_output_dir: 'allen_visbehave_swr_murphylab2024'
  
  # Session selection
  only_brain_observatory_sessions: False
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    sdk_cache_dir: '/space/scratch/allen_visbehave_data'
    input_dir: '${output_dir}/allen_visbehave_swr_murphylab2024'
    swr_output_dir: 'allen_visbehave_swr_murphylab2024'
  
  # Global ripple detection
  global_ripple:
    input_dir: '${output_dir}/allen_visbehave_swr_murphylab2024'
    output_dir: '.'
    global_rip_label: 'no_movement'