# Consolidated SWR Detection Pipeline Configuration

# General Settings
run_name: $RUN_NAME 
# Unified output directory
output_dir: $OUTPUT_DIR
# Dataset-specific pool sizes
pool_sizes:
  abi_visual_behaviour: 1
  abi_visual_coding: 1
  ibl: 1

# Thresholds (common across all pipelines)
gamma_event_thresh: 3
ripple_band_threshold: 2
movement_artifact_ripple_band_threshold: 2
merge_events_offset: 0.025  # For merging nearby events

# Paths to Filters
filters:
  gamma_filter: 'Filters/frank2008_gamma_1500hz_bandpass_filter.npz'
  sw_component_filter: 'Filters/sharpwave_componenet_8to40band_1500hz_band.npz'

# ABI-specific Settings (Allen Brain Institute)
abi_visual_coding:
  # Cache and data directories
  sdk_cache_dir: $ABI_VISUAL_CODING_SDK_CACHE
  swr_output_dir: 'allen_viscoding_swr_murphylab2024'
  
  # Session selection
  only_brain_observatory_sessions: False
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/allen_viscoding_swr_murphylab2024'
    swr_output_dir: 'allen_viscoding_swr_murphylab2024'
  
# ABI-specific Settings (Allen Brain Institute)
abi_visual_behaviour:
  # Cache and data directories
  sdk_cache_dir: $ABI_VISUAL_BEHAVIOUR_SDK_CACHE
  swr_output_dir: 'allen_visbehave_swr_murphylab2024'
  
  # Session selection
  only_brain_observatory_sessions: False
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/allen_visbehave_swr_murphylab2024'
    swr_output_dir: 'allen_visbehave_swr_murphylab2024'
  
# IBL-specific Settings
ibl:
  # Cache and data directories
  oneapi_cache_dir: $IBL_ONEAPI_CACHE
  swr_output_dir: 'ibl_swr_murphylab2024'
  
  # Input files
  session_npz_filepath: 'all_ibl_sessions_with_ca1.npz'
  
  # Session selection
  dont_wipe_these_sessions: []
  select_these_sessions: []
  
  # Filtering settings
  filtering:
    input_dir: '${output_dir}/ibl_swr_murphylab2024'
    swr_output_dir: 'ibl_swr_murphylab2024'
  
# Global SWR Detection Settings (common)
global_swr_detection:
  min_ca1_units: 0          # Minimum number of good units in CA1 to include a probe
  min_events_per_probe: 100  # Minimum number of events per probe
  min_filtered_events: 50    # Minimum number of events after filtering
  min_sw_power: 1.0          # Minimum sharpwave power (z-score)
  merge_window: 0.02         # Merge window for global events (in seconds)
  min_probe_count: 2         # Minimum number of probes for a global event
  exclude_gamma: true        # Whether to exclude events with gamma overlap
  exclude_movement: true     # Whether to exclude events with movement artifact overlap
  global_rip_label: "global" # Label to append to global event filenames