# config yaml

# detector
pool_size: 6
sdk_cache_dir: '/space/scratch/allen_visbehave_data'
output_dir: '/space/scratch/allen_visbehave_swr_data'
swr_output_dir: 'testing_dir'
run_name: 'final_run'
select_these_sessions: []
only_brain_observatory_sessions: True
dont_wipe_these_sessions: []
gamma_event_thresh: 3
gamma_filter_path: '/home/acampbell/NeuropixelsLFPOnRamp/PowerBandFilters/swr_detection_script_filters_1500Hz/frank2008_gamma_1500hz_bandpass_filter.npz'
theta_filter_path: '/home/acampbell/NeuropixelsLFPOnRamp/PowerBandFilters/swr_detection_script_filters_1500Hz/theta_1500hz_bandpass_filter.npz'
ripple_band_threshold: 2
movement_artifact_ripple_band_threshold: 2

# filtering
sdk_cache_dir_filter: '/space/scratch/allen_visbehave_data'
input_dir: '/space/scratch/allen_visbehave_swr_data/testing_dir'
output_dir_filter: '/space/scratch/allen_visbehave_swr_data/'
swr_output_dir: 'testing_dir_filtered'



# Global Ripple Detector
input_dir: '/space/scratch/allen_visbehave_swr_data/testing_dir_filtered'
output_dir: '.'
global_rip_label: 'no_movement_no_gamma'
minimum_ripple_num: 100
